/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaresucatronix.interfacegrafica;

import softwaresucatronix.bean.Funcionario;

/**
 *
 * @author T-Gamer
 */
public class TelaPrincipalVendedor extends javax.swing.JFrame {

    private final Funcionario funcionarioLogado;
    
    /**
     * Creates new form TelaPrincipalVendedor
     */
    public TelaPrincipalVendedor(Funcionario funcionario) {
        this.funcionarioLogado = funcionario;
        initComponents();
        switch (this.funcionarioLogado.getTipo()) {
            case "SUPERUSER":
                menCad.setEnabled(true);
                jMenuItem2.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem4.setEnabled(true);
                jMenuItem6.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenuItem3.setEnabled(true);
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenuItem13.setEnabled(true);
                jMenuItem11.setEnabled(true);
                jMenuItem10.setEnabled(true);
                jMenuItem12.setEnabled(true);
                menCad.setEnabled(true);
                jMenuItem9.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenuItem3.setEnabled(true);
                menCad.setEnabled(true);
                jMenuItem8.setEnabled(true);
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenuItem1.setEnabled(true);
                jMenuItem10.setEnabled(true);
                jMenuItem12.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem3.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem15.setEnabled(true);
                break;
            case "ADMINISTRADOR":
                menCad.setEnabled(true);
                jMenuItem2.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem4.setEnabled(true);
                jMenuItem6.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenuItem3.setEnabled(true);
                menCad.setEnabled(true);
                jMenuItem2.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem4.setEnabled(true);
                break;
            case "TÉCNICO":
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenuItem13.setEnabled(true);
                jMenuItem11.setEnabled(true);
                jMenuItem10.setEnabled(true);
                jMenuItem12.setEnabled(true);
                break;
            case "GESTOR":
                menCad.setEnabled(true);
                jMenuItem2.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem4.setEnabled(true);
                break;
            case "VENDEDOR":
                menCad.setEnabled(true);
                jMenuItem9.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem7.setEnabled(true);
                jMenuItem14.setEnabled(true);
                jMenuItem3.setEnabled(true);
                break;
            case "ALMOXARIFADO":
                menCad.setEnabled(true);
                jMenuItem8.setEnabled(true);
                jMenu3.setEnabled(true);
                jMenuItem5.setEnabled(true);
                jMenuItem1.setEnabled(true);
                jMenuItem10.setEnabled(true);
                jMenuItem12.setEnabled(true);
                jMenu4.setEnabled(true);
                jMenuItem3.setEnabled(true);
                jMenu2.setEnabled(true);
                jMenuItem15.setEnabled(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menCad = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        setSize(new java.awt.Dimension(800, 800));

        Desktop.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jMenu4.setText("Vendas");
        jMenu4.setEnabled(false);

        jMenuItem7.setText("Nova Venda/Orçamento");
        jMenuItem7.setEnabled(false);
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem14.setText("Orçamentos");
        jMenuItem14.setEnabled(false);
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem3.setText("Vendas");
        jMenuItem3.setEnabled(false);
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Consulta");
        jMenu2.setEnabled(false);

        jMenuItem4.setText("Funcionários");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Clientes");
        jMenuItem6.setEnabled(false);
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem15.setText("Fornecedores");
        jMenuItem15.setEnabled(false);
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estoque");
        jMenu3.setEnabled(false);

        jMenuItem5.setText("Abrir Estoque");
        jMenuItem5.setEnabled(false);
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem1.setText("Adicionar Produto");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem10.setText("Fazer pedido");
        jMenuItem10.setEnabled(false);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem13.setText("Consultar pedidos");
        jMenuItem13.setEnabled(false);
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem11.setText("Solicitar do almoxarifado");
        jMenuItem11.setEnabled(false);
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Consultar solicitações");
        jMenuItem12.setEnabled(false);
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        menCad.setText("Cadastro");
        menCad.setEnabled(false);

        jMenuItem2.setText("Funcionários");
        jMenuItem2.setEnabled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menCad.add(jMenuItem2);

        jMenuItem8.setText("Fornecedores");
        jMenuItem8.setEnabled(false);
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menCad.add(jMenuItem8);

        jMenuItem9.setText("Clientes");
        jMenuItem9.setEnabled(false);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menCad.add(jMenuItem9);

        jMenuBar1.add(menCad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(788, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Desktop.removeAll();
        TelaFuncionarios funcionario = new TelaFuncionarios();
        funcionario.setVisible(true);
        Desktop.add(funcionario);        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Desktop.removeAll();
        TelaCadastrarProdutos produto = new TelaCadastrarProdutos();
        produto.setVisible(true);
        Desktop.add(produto);        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Desktop.removeAll();
        TelaEstoque estoque = new TelaEstoque();
        estoque.setVisible(true);
        Desktop.add(estoque);   
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Desktop.removeAll();
        TelaConsultaVendas venda = new TelaConsultaVendas(true, Desktop);
        venda.setVisible(true);
        Desktop.add(venda);  
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Desktop.removeAll();
        TelaConsultaFuncionarios funcionario = new TelaConsultaFuncionarios();
        funcionario.setVisible(true);
        Desktop.add(funcionario);  
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Desktop.removeAll();
        TelaConsultaClientes cliente= new TelaConsultaClientes();
        cliente.setVisible(true);
        Desktop.add(cliente);        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Desktop.removeAll();
        TelaNovaVenda venda= new TelaNovaVenda(this.funcionarioLogado);
        venda.setVisible(true);
        Desktop.add(venda); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Desktop.removeAll();
        TelaFornecedores fornecedor = new TelaFornecedores();
        fornecedor.setVisible(true);
        Desktop.add(fornecedor);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Desktop.removeAll();
        TelaClientes cliente = new TelaClientes();
        cliente.setVisible(true);
        Desktop.add(cliente);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Desktop.removeAll();
        TelaNovoPedido pedido = new TelaNovoPedido(this.funcionarioLogado);
        pedido.setVisible(true);
        Desktop.add(pedido);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Desktop.removeAll();
        TelaNovaSolicitacao solicitacao = new TelaNovaSolicitacao(this.funcionarioLogado);
        solicitacao.setVisible(true);
        Desktop.add(solicitacao);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Desktop.removeAll();
        TelaConsultaSolicitacoes solicitacao = new TelaConsultaSolicitacoes(Desktop);
        solicitacao.setVisible(true);
        Desktop.add(solicitacao);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Desktop.removeAll();
        TelaConsultaPedidos pedido = new TelaConsultaPedidos(Desktop);
        pedido.setVisible(true);
        Desktop.add(pedido);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Desktop.removeAll();
        TelaConsultaVendas venda = new TelaConsultaVendas(false, Desktop);
        venda.setVisible(true);
        Desktop.add(venda);  
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Desktop.removeAll();
        TelaConsultaFornecedores fornecedor= new TelaConsultaFornecedores();
        fornecedor.setVisible(true);
        Desktop.add(fornecedor); 
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalVendedor(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menCad;
    // End of variables declaration//GEN-END:variables
}
